name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-agent:
    uses: maheshannavaram92-arch/pr-review-workflows/.github/workflows/pr-agent.yml@main
    with:
      auto_describe: true
      auto_improve: true
      auto_review: true
      feedback: true
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PR_AGENT_WRAPPER_PRIVATE_KEY: ${{ secrets.PR_AGENT_WRAPPER_PRIVATE_KEY }}
